### ISSUE TITLE
[Feat] 악보 오브젝트 애니메이션

### ISSUE THREAD

**Issue by RayBean1022** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16#41]
# 이슈 설명
Score prefab이 경직되어 있어 Idle 모션이 있으면 좋을 것으로 보임

참고 ->
<img width="789" alt="image" src="https://github.com/user-attachments/assets/f733cd0e-7054-4cc9-8340-c3dda03423a7">
_Originally posted by @silee1103 in https://github.com/2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16/pull/13#discussion_r1861989414_ 

# 필요 작업
모션 구현

**Comment by silee1103** [comment]
#59
