### ISSUE TITLE
[Bug] PressurePlate가 control의 object detector도 감지하는 버그

### ISSUE THREAD

**Issue by silee1103** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16#43]
# 이슈 설명
PressurePlate가 control의 object detector도 감지하는 버그가 존재한다.
평상시에는 문제가 없으나 player가 PressurePlate 주변에서 돌 위에 올라가는 등의 행위를 하면 PressurePlate가 이를 인식한다.

# 필요 작업
object detector에 Layer를 지정해 그 layer는 pressure plate의 raycast가 감지하지 않도록 한다.

**Comment by ygr4789** [comment]
object detector가 개발 과정에서 Ignore Raycast 레이어로 분류되어 더 이상 감지되지 않음
