### ISSUE TITLE
[Feat] 문을 열 때 연출, 들어간 후 연출 추가

### ISSUE THREAD

**Issue by guzus** [2024FALL-SWPP/team-project-for-2024-fall-swpp-team-16#44]
https://2024fallswppimo.slack.com/archives/C07RC4RAZTJ/p1732817444170889?thread_ts=1732799219.311809&cid=C07RC4RAZTJ

**Comment by silee1103** [comment]
문 열기 위해 연주할 때 다른 곳으로 이동 가능합니다.
이것도 제약을 걸어야 할 것 같습니다
